import type { Playlist } from './types';

export const MAIN_VIDEO_URL =
  'https://data-h03.fra1.cdn.digitaloceanspaces.com/FIFA';
export const WS_VIDEO_URL =
  'https://data-h03.fra1.cdn.digitaloceanspaces.com/ws.mp4';

const timeToSeconds = (time: string): number => {
  const parts = time.split(':').map(Number);
  if (parts.length === 2) {
    return parts[0] * 60 + parts[1];
  }
  return 0;
};

export const PLAYLIST: Playlist = {
  id: 'pl-fifa-11-plus-full',
  name: 'FIFA 11+ Komplettes Programm',
  description:
    'Das komplette FIFA 11+ Verletzungspräventionsprogramm mit Laufen, Kraft, Plyometrie und Gleichgewichtsübungen.',
  videos: [
    {
      id: 'header-part-1',
      title: 'Teil 1: Laufübungen',
      description: '',
      timestamp: '',
      isHeader: true,
    },
    {
      id: `fifa11-20`,
      title: '1. Geradeaus',
      description: '2 Mal durchführen.',
      timestamp: '00:20',
      startTime: timeToSeconds('00:20'),
    },
    {
      id: `fifa11-39`,
      title: '2. Hüftdrehung nach aussen',
      description: '2 Mal durchführen.',
      timestamp: '00:39',
      startTime: timeToSeconds('00:39'),
    },
    {
      id: `fifa11-54`,
      title: '3. Hüftdrehung nach innen',
      description: '2 Mal durchführen.',
      timestamp: '00:54',
      startTime: timeToSeconds('00:54'),
    },
    {
      id: `fifa11-71`,
      title: '4. Seitgalopp',
      description: '2 Mal durchführen.',
      timestamp: '01:11',
      startTime: timeToSeconds('01:11'),
    },
    {
      id: `fifa11-95`,
      title: '5. Schulterkontakt',
      description: '2 Mal durchführen.',
      timestamp: '01:35',
      startTime: timeToSeconds('01:35'),
    },
    {
      id: `fifa11-116`,
      title: '6. Vor- und Zurücksprinten',
      description: '2 Mal durchführen.',
      timestamp: '01:56',
      startTime: timeToSeconds('01:56'),
    },
    {
      id: 'header-part-2',
      title: 'Teil 2: Kraft, Plyometrie und Gleichgewicht',
      description: '',
      timestamp: '',
      isHeader: true,
    },
    {
      id: `fifa11-180`,
      title: '7.1 Unterarmstütz Halten',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden).',
      timestamp: '03:00',
      startTime: timeToSeconds('03:00'),
    },
    {
      id: `fifa11-210`,
      title: '7.2 Unterarmstütz Beine wechselnd anheben',
      description: '3 Wiederholungen (jeweils 40–60 Sekunden).',
      timestamp: '03:30',
      startTime: timeToSeconds('03:30'),
    },
    {
      id: `fifa11-246`,
      title: '7.3 Unterarmstütz Bein anheben und halten',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '04:06',
      startTime: timeToSeconds('04:06'),
    },
    {
      id: `fifa11-287`,
      title: '8.1 Seitlicher Unterarmstütz Halten',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '04:47',
      startTime: timeToSeconds('04:47'),
    },
    {
      id: `fifa11-320`,
      title: '8.2 Seitlicher Unterarmstütz Hüfte heben und senken',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '05:20',
      startTime: timeToSeconds('05:20'),
    },
    {
      id: `fifa11-357`,
      title: '8.3 Seitlicher Unterarmstütz Bein heben und senken',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '05:57',
      startTime: timeToSeconds('05:57'),
    },
    {
      id: `fifa11-398`,
      title: '9.1 Oberschenkelrückseite Anfänger',
      description: '1 Mal (3–5 Wiederholungen).',
      timestamp: '06:38',
      startTime: timeToSeconds('06:38'),
    },
    {
      id: `fifa11-411`,
      title: '9.2 Oberschenkelrückseite Fortgeschritten',
      description: '1 Mal (7–10 Wiederholungen).',
      timestamp: '06:51',
      startTime: timeToSeconds('06:51'),
    },
    {
      id: `fifa11-420`,
      title: '9.3 Oberschenkelrückseite Topfit',
      description: '1 Mal (mindestens 12–15 Wiederholungen).',
      timestamp: '07:00',
      startTime: timeToSeconds('07:00'),
    },
    {
      id: `fifa11-438`,
      title: '10.1 Einbeinstand mit dem Ball',
      description: '2 Mal (jeweils 30 Sekunden auf jedem Bein).',
      timestamp: '07:18',
      startTime: timeToSeconds('07:18'),
    },
    {
      id: `fifa11-470`,
      title: '10.2 Einbeinstand Ball gegenseitig zuwerfen',
      description: '2 Mal (jeweils 30 Sekunden auf jedem Bein).',
      timestamp: '07:50',
      startTime: timeToSeconds('07:50'),
    },
    {
      id: `fifa11-502`,
      title: '10.3 Einbeinstand Gleichgewicht testen',
      description: '2 Mal (jeweils 30 Sekunden auf jedem Bein).',
      timestamp: '08:22',
      startTime: timeToSeconds('08:22'),
    },
    {
      id: `fifa11-533`,
      title: '11.1 Kniebeugen auf die Zehenspitzen',
      description: '2 Mal (jeweils 30 Sekunden).',
      timestamp: '08:53',
      startTime: timeToSeconds('08:53'),
    },
    {
      id: `fifa11-572`,
      title: '11.2 Kniebeugen Ausfallschritte',
      description: '2 Mal (jeweils 10 Schritte mit jedem Bein).',
      timestamp: '09:32',
      startTime: timeToSeconds('09:32'),
    },
    {
      id: `fifa11-603`,
      title: '11.3 Kniebeugen auf einem Bein',
      description: '2 Mal (jeweils 10 Mal auf jedem Bein).',
      timestamp: '10:03',
      startTime: timeToSeconds('10:03'),
    },
    {
      id: `fifa11-639`,
      title: '12.1 Springen Sprünge nach oben',
      description: '2 Mal (30 Sekunden).',
      timestamp: '10:39',
      startTime: timeToSeconds('10:39'),
    },
    {
      id: `fifa11-673`,
      title: '12.2 Springen Sprünge zur Seite',
      description: '2 Mal (30 Sekunden).',
      timestamp: '11:13',
      startTime: timeToSeconds('11:13'),
    },
    {
      id: `fifa11-708`,
      title: '12.3 Springen Kreuzsprünge',
      description: '2 Mal (30 Sekunden).',
      timestamp: '11:48',
      startTime: timeToSeconds('11:48'),
    },
    {
      id: 'header-part-3',
      title: 'Teil 3: Laufübungen',
      description: '',
      timestamp: '',
      isHeader: true,
    },
    {
      id: `fifa11-775`,
      title: '13. Laufen über das Spielfeld',
      description: '2 Mal durchführen.',
      timestamp: '12:55',
      startTime: timeToSeconds('12:55'),
    },
    {
      id: `fifa11-798`,
      title: '14. Laufen Hoch-Weit-Sprünge',
      description: '2 Mal durchführen.',
      timestamp: '13:18',
      startTime: timeToSeconds('13:18'),
    },
    {
      id: `fifa11-824`,
      title: '15. Laufen Richtungswechsel',
      description: '2 Mal durchführen.',
      timestamp: '13:44',
      startTime: timeToSeconds('13:44'),
    },
  ],
};

export const WS_PLAYLIST: Playlist = {
  id: 'pl-fifa-11-plus-ws',
  name: 'FIFA 11+ World Soccer Programm',
  description:
    'Alternatives FIFA 11+ Verletzungspräventionsprogramm mit aktualisierten Übungen und Demonstrationen.',
  videos: [
    {
      id: 'header-part-1-ws',
      title: 'Teil 1: Laufübungen',
      description: '',
      timestamp: '',
      isHeader: true,
    },
    {
      id: 'ws-24',
      title: '1. Geradeaus',
      description: '2 Mal durchführen.',
      timestamp: '00:24',
      startTime: timeToSeconds('00:24'),
    },
    {
      id: 'ws-37',
      title: '2. Hüftdrehung nach aussen',
      description: '2 Mal durchführen.',
      timestamp: '00:37',
      startTime: timeToSeconds('00:37'),
    },
    {
      id: 'ws-60',
      title: '3. Hüftdrehung nach innen',
      description: '2 Mal durchführen.',
      timestamp: '01:00',
      startTime: timeToSeconds('01:00'),
    },
    {
      id: 'ws-83',
      title: '4. Seitgalopp',
      description: '2 Mal durchführen.',
      timestamp: '01:23',
      startTime: timeToSeconds('01:23'),
    },
    {
      id: 'ws-114',
      title: '5. Schulterkontakt',
      description: '2 Mal durchführen.',
      timestamp: '01:54',
      startTime: timeToSeconds('01:54'),
    },
    {
      id: 'ws-144',
      title: '6. Vor- und Zurücksprinten',
      description: '2 Mal durchführen.',
      timestamp: '02:24',
      startTime: timeToSeconds('02:24'),
    },
    {
      id: 'ws-170',
      title: '7. Laufen über das Spielfeld',
      description: '2 Mal durchführen.',
      timestamp: '02:50',
      startTime: timeToSeconds('02:50'),
    },
    {
      id: 'ws-183',
      title: '8. Laufen Hoch-Weit-Sprünge',
      description: '2 Mal durchführen.',
      timestamp: '03:03',
      startTime: timeToSeconds('03:03'),
    },
    {
      id: 'ws-198',
      title: '9. Laufen Richtungswechsel',
      description: '2 Mal durchführen.',
      timestamp: '03:18',
      startTime: timeToSeconds('03:18'),
    },
    {
      id: 'header-part-2-ws',
      title: 'Teil 2: Kraft, Plyometrie und Gleichgewicht',
      description: '',
      timestamp: '',
      isHeader: true,
    },
    {
      id: 'ws-227',
      title: '10. Unterarmstütz: Level 1 - Halten',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden).',
      timestamp: '03:47',
      startTime: timeToSeconds('03:47'),
    },
    {
      id: 'ws-237',
      title: '11. Unterarmstütz: Level 2 - Beine wechselnd anheben',
      description: '3 Wiederholungen (jeweils 40–60 Sekunden).',
      timestamp: '03:57',
      startTime: timeToSeconds('03:57'),
    },
    {
      id: 'ws-248',
      title: '12. Unterarmstütz: Level 3 - Bein anheben und halten',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '04:08',
      startTime: timeToSeconds('04:08'),
    },
    {
      id: 'ws-258',
      title: '13. Seitlicher Unterarmstütz: Level 1 - Halten',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '04:18',
      startTime: timeToSeconds('04:18'),
    },
    {
      id: 'ws-268',
      title: '14. Seitlicher Unterarmstütz: Level 2 - Hüfte heben und senken',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '04:28',
      startTime: timeToSeconds('04:28'),
    },
    {
      id: 'ws-279',
      title: '15. Seitlicher Unterarmstütz: Level 3 - mit Beinhebung',
      description: '3 Wiederholungen (jeweils 20–30 Sekunden auf jeder Seite).',
      timestamp: '04:39',
      startTime: timeToSeconds('04:39'),
    },
    {
      id: 'ws-290',
      title: '16. Oberschenkelrückseite: Level 1',
      description: '1 Mal (3–5 Wiederholungen).',
      timestamp: '04:50',
      startTime: timeToSeconds('04:50'),
    },
    {
      id: 'ws-304',
      title: '17. Oberschenkelrückseite: Level 2',
      description: '1 Mal (7–10 Wiederholungen).',
      timestamp: '05:04',
      startTime: timeToSeconds('05:04'),
    },
    {
      id: 'ws-316',
      title: '18. Oberschenkelrückseite: Level 3',
      description: '1 Mal (mindestens 12–15 Wiederholungen).',
      timestamp: '05:16',
      startTime: timeToSeconds('05:16'),
    },
    {
      id: 'ws-328',
      title: '19. Kopenhagen Adduktoren: Level 1 - Seitliche Beinhebung',
      description: '2 Mal (jeweils 30 Sekunden auf jeder Seite).',
      timestamp: '05:28',
      startTime: timeToSeconds('05:28'),
    },
    {
      id: 'ws-339',
      title: '20. Kopenhagen Adduktoren: Level 2 - Oberes Knie gestützt',
      description: '2 Mal (jeweils 30 Sekunden auf jeder Seite).',
      timestamp: '05:39',
      startTime: timeToSeconds('05:39'),
    },
    {
      id: 'ws-352',
      title: '21. Kopenhagen Adduktoren: Level 3 - Oberer Knöchel gestützt',
      description: '2 Mal (jeweils 30 Sekunden auf jeder Seite).',
      timestamp: '05:52',
      startTime: timeToSeconds('05:52'),
    },
  ],
};
