import type { Drill } from './types';

// Cloudinary video URLs from warmup_playlist_cloudinary.json
const CLOUDINARY_VIDEO_URLS: Record<string, string> = {
  '01_Laufen_Geradeaus': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971879/warmup_playlist/01_Laufen_Geradeaus.mp4',
  '02_Laufen_Hueftdrehung_nach_Aussen': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971885/warmup_playlist/02_Laufen_Hueftdrehung_nach_Aussen.mp4',
  '03_Laufen_Hueftdrehung_nach_Innen': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971891/warmup_playlist/03_Laufen_Hueftdrehung_nach_Innen.mp4',
  '04_Laufen_Seitgalopp': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971896/warmup_playlist/04_Laufen_Seitgalopp.mp4',
  '05_Laufen_Schulterkontakt': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971904/warmup_playlist/05_Laufen_Schulterkontakt.mp4',
  '06_Laufen_Vor_und_Zurueck_Sprinten': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971912/warmup_playlist/06_Laufen_Vor_und_Zurueck_Sprinten.mp4',
  '07_Unterarmstuetz_Level_1_Halten': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971918/warmup_playlist/07_Unterarmstuetz_Level_1_Halten.mp4',
  '08_Unterarmstuetz_Level_2_Beine_Wechselnd_Auheben': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971930/warmup_playlist/08_Unterarmstuetz_Level_2_Beine_Wechselnd_Auheben.mp4',
  '09_Unterarmstuetz_Level_3_Bein_Auheben_und_Halten': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971937/warmup_playlist/09_Unterarmstuetz_Level_3_Bein_Auheben_und_Halten.mp4',
  '10_Seitlicher_Unterarmstuetz_Level_1_Halten': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971945/warmup_playlist/10_Seitlicher_Unterarmstuetz_Level_1_Halten.mp4',
  '11_Seitlicher_Unterarmstuetz_Level_2_Huefte_Heben_und_Senken': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971951/warmup_playlist/11_Seitlicher_Unterarmstuetz_Level_2_Huefte_Heben_und_Senken.mp4',
  '12_Seitlicher_Unterarmstuetz_Level_3_Bein_Heben_und_Senken': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971959/warmup_playlist/12_Seitlicher_Unterarmstuetz_Level_3_Bein_Heben_und_Senken.mp4',
  '13_Oberschenkelrueckseite_Level_1_Anfaenger': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971966/warmup_playlist/13_Oberschenkelrueckseite_Level_1_Anfaenger.mp4',
  '14_Oberschenkelrueckseite_Level_2_Fortgeschrittene': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971973/warmup_playlist/14_Oberschenkelrueckseite_Level_2_Fortgeschrittene.mp4',
  '15_Oberschenkelrueckseite_Level_3_Topfit': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971982/warmup_playlist/15_Oberschenkelrueckseite_Level_3_Topfit.mp4',
  '16_Einbeinstand_Level_1_Mit_dem_Ball': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760971991/warmup_playlist/16_Einbeinstand_Level_1_Mit_dem_Ball.mp4',
  '17_Einbeinstand_Level_2_Ball_Gegenseitig_Zuwerfen': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760972003/warmup_playlist/17_Einbeinstand_Level_2_Ball_Gegenseitig_Zuwerfen.mp4',
  '18_Einbeinstand_Level_3_Gleichgewicht_Testen': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760972010/warmup_playlist/18_Einbeinstand_Level_3_Gleichgewicht_Testen.mp4',
  '19_Kniebeugen_Level_1_Auf_die_Zehenspitzen': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760972019/warmup_playlist/19_Kniebeugen_Level_1_Auf_die_Zehenspitzen.mp4',
  '20_Kniebeugen_Level_2_Ausfallschritte': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760972027/warmup_playlist/20_Kniebeugen_Level_2_Ausfallschritte.mp4',
  '21_Kniebeugen_Level_3_Auf_einem_Bein': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760972039/warmup_playlist/21_Kniebeugen_Level_3_Auf_einem_Bein.mp4',
  '22_Springen_Level_1_Spruenge_nach_Oben': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760972044/warmup_playlist/22_Springen_Level_1_Spruenge_nach_Oben.mp4',
  '23_Springen_Level_2_Spruenge_zur_Seite': 'https://res.cloudinary.com/dg8zbx8ja/video/upload/v1760972050/warmup_playlist/23_Springen_Level_2_Spruenge_zur_Seite.mp4',
};

export const WARMUP_DRILLS: Drill[] = [
  {
    id: 1,
    name: 'Laufen - Geradeaus',
    videoUrl: CLOUDINARY_VIDEO_URLS['01_Laufen_Geradeaus'],
    videoFile: '01_Laufen_Geradeaus.mp4',
    description: 'Laufen Sie geradeaus auf der Stelle. Fokus auf gleichmäßige Bewegung.',
  },
  {
    id: 2,
    name: 'Laufen - Hüftdrehung nach Außen',
    videoUrl: CLOUDINARY_VIDEO_URLS['02_Laufen_Hueftdrehung_nach_Aussen'],
    videoFile: '02_Laufen_Hueftdrehung_nach_Aussen.mp4',
    description: 'Laufen Sie auf der Stelle mit Hüftdrehungen nach außen.',
  },
  {
    id: 3,
    name: 'Laufen - Hüftdrehung nach Innen',
    videoUrl: CLOUDINARY_VIDEO_URLS['03_Laufen_Hueftdrehung_nach_Innen'],
    videoFile: '03_Laufen_Hueftdrehung_nach_Innen.mp4',
    description: 'Laufen Sie auf der Stelle mit Hüftdrehungen nach innen.',
  },
  {
    id: 4,
    name: 'Laufen - Seitgalopp',
    videoUrl: CLOUDINARY_VIDEO_URLS['04_Laufen_Seitgalopp'],
    videoFile: '04_Laufen_Seitgalopp.mp4',
    description: 'Führen Sie Seitgalopp-Bewegungen auf der Stelle aus.',
  },
  {
    id: 5,
    name: 'Laufen - Schulterkontakt',
    videoUrl: CLOUDINARY_VIDEO_URLS['05_Laufen_Schulterkontakt'],
    videoFile: '05_Laufen_Schulterkontakt.mp4',
    description: 'Laufen Sie auf der Stelle mit Schulterkontakt nach vorne.',
  },
  {
    id: 6,
    name: 'Laufen - Vor und Zurück Sprinten',
    videoUrl: CLOUDINARY_VIDEO_URLS['06_Laufen_Vor_und_Zurueck_Sprinten'],
    videoFile: '06_Laufen_Vor_und_Zurueck_Sprinten.mp4',
    description: 'Sprinten Sie vor und zurück auf der Stelle.',
  },
  {
    id: 7,
    name: 'Unterarmstütz - Level 1 Halten',
    videoUrl: CLOUDINARY_VIDEO_URLS['07_Unterarmstuetz_Level_1_Halten'],
    videoFile: '07_Unterarmstuetz_Level_1_Halten.mp4',
    description: 'Halten Sie die Unterarmstütz-Position.',
    level: '1',
  },
  {
    id: 8,
    name: 'Unterarmstütz - Level 2 Beine Wechselnd Anheben',
    videoUrl: CLOUDINARY_VIDEO_URLS['08_Unterarmstuetz_Level_2_Beine_Wechselnd_Auheben'],
    videoFile: '08_Unterarmstuetz_Level_2_Beine_Wechselnd_Auheben.mp4',
    description: 'Heben Sie die Beine wechselnd in der Unterarmstütz-Position an.',
    level: '2',
  },
  {
    id: 9,
    name: 'Unterarmstütz - Level 3 Bein Anheben und Halten',
    videoUrl: CLOUDINARY_VIDEO_URLS['09_Unterarmstuetz_Level_3_Bein_Auheben_und_Halten'],
    videoFile: '09_Unterarmstuetz_Level_3_Bein_Auheben_und_Halten.mp4',
    description: 'Heben Sie ein Bein an und halten Sie die Position.',
    level: '3',
  },
  {
    id: 10,
    name: 'Seitlicher Unterarmstütz - Level 1 Halten',
    videoUrl: CLOUDINARY_VIDEO_URLS['10_Seitlicher_Unterarmstuetz_Level_1_Halten'],
    videoFile: '10_Seitlicher_Unterarmstuetz_Level_1_Halten.mp4',
    description: 'Halten Sie die seitliche Unterarmstütz-Position.',
    level: '1',
  },
  {
    id: 11,
    name: 'Seitlicher Unterarmstütz - Level 2 Hüfte Heben und Senken',
    videoUrl: CLOUDINARY_VIDEO_URLS['11_Seitlicher_Unterarmstuetz_Level_2_Huefte_Heben_und_Senken'],
    videoFile: '11_Seitlicher_Unterarmstuetz_Level_2_Huefte_Heben_und_Senken.mp4',
    description: 'Heben und senken Sie die Hüfte in seitlicher Unterarmstütz-Position.',
    level: '2',
  },
  {
    id: 12,
    name: 'Seitlicher Unterarmstütz - Level 3 Bein Heben und Senken',
    videoUrl: CLOUDINARY_VIDEO_URLS['12_Seitlicher_Unterarmstuetz_Level_3_Bein_Heben_und_Senken'],
    videoFile: '12_Seitlicher_Unterarmstuetz_Level_3_Bein_Heben_und_Senken.mp4',
    description: 'Heben und senken Sie das obere Bein in seitlicher Unterarmstütz-Position.',
    level: '3',
  },
  {
    id: 13,
    name: 'Oberschenkelrückseite - Level 1 Anfänger',
    videoUrl: CLOUDINARY_VIDEO_URLS['13_Oberschenkelrueckseite_Level_1_Anfaenger'],
    videoFile: '13_Oberschenkelrueckseite_Level_1_Anfaenger.mp4',
    description: 'Dehnung der Oberschenkelrückseite für Anfänger.',
    level: '1',
  },
  {
    id: 14,
    name: 'Oberschenkelrückseite - Level 2 Fortgeschrittene',
    videoUrl: CLOUDINARY_VIDEO_URLS['14_Oberschenkelrueckseite_Level_2_Fortgeschrittene'],
    videoFile: '14_Oberschenkelrueckseite_Level_2_Fortgeschrittene.mp4',
    description: 'Dehnung der Oberschenkelrückseite für Fortgeschrittene.',
    level: '2',
  },
  {
    id: 15,
    name: 'Oberschenkelrückseite - Level 3 Topfit',
    videoUrl: CLOUDINARY_VIDEO_URLS['15_Oberschenkelrueckseite_Level_3_Topfit'],
    videoFile: '15_Oberschenkelrueckseite_Level_3_Topfit.mp4',
    description: 'Dehnung der Oberschenkelrückseite für Topfit-Level.',
    level: '3',
  },
  {
    id: 16,
    name: 'Einbeinstand - Level 1 Mit dem Ball',
    videoUrl: CLOUDINARY_VIDEO_URLS['16_Einbeinstand_Level_1_Mit_dem_Ball'],
    videoFile: '16_Einbeinstand_Level_1_Mit_dem_Ball.mp4',
    description: 'Einbeinstand mit Ball zur Stabilisierung.',
    level: '1',
  },
  {
    id: 17,
    name: 'Einbeinstand - Level 2 Ball Gegenseitig Zuwerfen',
    videoUrl: CLOUDINARY_VIDEO_URLS['17_Einbeinstand_Level_2_Ball_Gegenseitig_Zuwerfen'],
    videoFile: '17_Einbeinstand_Level_2_Ball_Gegenseitig_Zuwerfen.mp4',
    description: 'Einbeinstand mit gegenseitigem Zuwerfen des Balls.',
    level: '2',
  },
  {
    id: 18,
    name: 'Einbeinstand - Level 3 Gleichgewicht Testen',
    videoUrl: CLOUDINARY_VIDEO_URLS['18_Einbeinstand_Level_3_Gleichgewicht_Testen'],
    videoFile: '18_Einbeinstand_Level_3_Gleichgewicht_Testen.mp4',
    description: 'Gleichgewichtsübung auf einem Bein mit erhöhter Schwierigkeit.',
    level: '3',
  },
  {
    id: 19,
    name: 'Kniebeugen - Level 1 Auf die Zehenspitzen',
    videoUrl: CLOUDINARY_VIDEO_URLS['19_Kniebeugen_Level_1_Auf_die_Zehenspitzen'],
    videoFile: '19_Kniebeugen_Level_1_Auf_die_Zehenspitzen.mp4',
    description: 'Kniebeugen mit anschließendem Aufstehen auf die Zehenspitzen.',
    level: '1',
  },
  {
    id: 20,
    name: 'Kniebeugen - Level 2 Ausfallschritte',
    videoUrl: CLOUDINARY_VIDEO_URLS['20_Kniebeugen_Level_2_Ausfallschritte'],
    videoFile: '20_Kniebeugen_Level_2_Ausfallschritte.mp4',
    description: 'Kniebeugen mit Ausfallschritten.',
    level: '2',
  },
  {
    id: 21,
    name: 'Kniebeugen - Level 3 Auf einem Bein',
    videoUrl: CLOUDINARY_VIDEO_URLS['21_Kniebeugen_Level_3_Auf_einem_Bein'],
    videoFile: '21_Kniebeugen_Level_3_Auf_einem_Bein.mp4',
    description: 'Einbeinige Kniebeugen für Fortgeschrittene.',
    level: '3',
  },
  {
    id: 22,
    name: 'Springen - Level 1 Sprünge nach Oben',
    videoUrl: CLOUDINARY_VIDEO_URLS['22_Springen_Level_1_Spruenge_nach_Oben'],
    videoFile: '22_Springen_Level_1_Spruenge_nach_Oben.mp4',
    description: 'Vertikale Sprünge mit beidbeiniger Landung.',
    level: '1',
  },
  {
    id: 23,
    name: 'Springen - Level 2 Sprünge zur Seite',
    videoUrl: CLOUDINARY_VIDEO_URLS['23_Springen_Level_2_Spruenge_zur_Seite'],
    videoFile: '23_Springen_Level_2_Spruenge_zur_Seite.mp4',
    description: 'Seitliche Sprünge mit stabilisierender Landung.',
    level: '2',
  },
];

export const getDrillById = (id: number): Drill | undefined => {
  return WARMUP_DRILLS.find(drill => drill.id === id);
};

export const getDrillsByLevel = (level: string): Drill[] => {
  return WARMUP_DRILLS.filter(drill => drill.level === level);
};
